import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SRC_DIR = path.join(__dirname, '../src');
const OUTPUT_FILE = path.join(__dirname, '../src/data/sourceCodeManifest.js');

const IGNORE_DIRS = ['node_modules', 'dist', 'build', '.git', 'assets', 'data']; // Ignore data to avoid self-reference loop
const INCLUDE_EXTS = ['.js', '.jsx', '.css'];

function getAllFiles(dirPath, arrayOfFiles) {
    const files = fs.readdirSync(dirPath);

    arrayOfFiles = arrayOfFiles || [];

    files.forEach(function (file) {
        const fullPath = path.join(dirPath, file);
        if (fs.statSync(fullPath).isDirectory()) {
            if (!IGNORE_DIRS.includes(file)) {
                arrayOfFiles = getAllFiles(fullPath, arrayOfFiles);
            }
        } else {
            if (INCLUDE_EXTS.includes(path.extname(file))) {
                // Exclude the output file itself if it accidentally gets picked up (though it's in IGNORE_DIRS 'data')
                if (fullPath !== OUTPUT_FILE) {
                    arrayOfFiles.push(fullPath);
                }
            }
        }
    });

    return arrayOfFiles;
}

const files = getAllFiles(SRC_DIR);

const imports = [];
const manifestItems = [];

files.forEach((file, index) => {
    // Create relative path for import
    // e.g. ../components/AdminPanel.jsx?raw
    // We are in scripts/ so we need relative to OUTPUT_FILE (src/data/...)
    // Actually, the generated file is in src/data.
    // The relative path from src/data to src/components/AdminPanel.jsx is ../components/AdminPanel.jsx

    const relativeFromSrc = path.relative(path.join(SRC_DIR, 'data'), file).replace(/\\/g, '/');
    const importName = `File${index}`;

    imports.push(`import ${importName} from './${relativeFromSrc}?raw';`);

    // Create readable title/desc
    const fileName = path.basename(file);
    const relativePathNice = path.relative(SRC_DIR, file).replace(/\\/g, '/');

    manifestItems.push(`    {
        id: 'file_${index}_${fileName.replace(/\./g, '_')}',
        filePath: 'src/${relativePathNice}',
        title: '${fileName}',
        description: 'Source code for src/${relativePathNice}',
        category: 'Source Code',
        content: ${importName}
    }`);
});

const fileContent = `
// SNAPSHOT OF SOURCE CODE FOR RAG INDEXING
// This file is auto-generated by scripts/generateManifest.js
// Do not edit manually.

${imports.join('\n')}

export const SOURCE_CODE_MANIFEST = [
    ${manifestItems.join(',\n')}
];
`;

fs.writeFileSync(OUTPUT_FILE, fileContent);
console.log(`Generated manifest with ${files.length} files at ${OUTPUT_FILE} `);
